name: MacOS Installer
run-name: ${{ inputs.fracktory_conan_version || 'Commit Triggered Build' }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      fracktory_conan_version:
        description: 'Fracktory Conan Version'
        default: 'fracktory/latest@fracktal/testing'
        required: true
        type: string

      conan_args:
        description: 'Conan args: e.g.: --require-override'
        default: ''
        required: false
        type: string

      enterprise:
        description: 'Build Fracktory as an Enterprise edition'
        default: false
        required: true
        type: boolean

      staging:
        description: 'Use staging API'
        default: false
        required: true
        type: boolean

      architecture:
        description: 'Architecture'
        required: true
        default: 'ARM64'
        type: choice
        options:
          - X64
          - ARM64

      operating_system:
        description: 'OS'
        required: true
        default: 'self-hosted-ARM64'
        type: choice
        options:
          - self-hosted-X64
          - self-hosted-ARM64
          - macos-12

  push:
    branches:
      - mac_test

jobs:
  macos-installer:
    uses: FracktalWorks/Fracktory-5/.github/workflows/fracktory-installer-macos.yml@main
    with:
      cura_conan_version: ${{ inputs.fracktory_conan_version || 'fracktory/latest@fracktal/testing' }}
      conan_args: ${{ inputs.conan_args || '' }}
      enterprise: ${{ inputs.enterprise || false }}
      staging: ${{ inputs.staging || false }}
      architecture: ${{ inputs.architecture || 'ARM64' }}
      operating_system: ${{ inputs.operating_system || 'macos-12' }}
    secrets: inherit
